### ISSUE TITLE
[Opti] foreach

### ISSUE THREAD

**Issue by Shadownest** [jeremyl67/Mission-to-Mars#3]
Quelques optimisations sont réalisables vis à vis de l'utilisation de la boucle foreach dans les fichiers suivants :
Mission-to-Mars/MVC/apps/traitement_login-register.php
Mission-to-Mars/MVC/apps/recherche.php
Mission-to-Mars/MVC/apps/list.php

A transformer en boucle while ou for pour gagner en performance !

**Comment by Cybelius** [comment]
ok c'est fait !
